# Site settings
title: Rakefire
email: contact@rakefire.io
description: > # this means to ignore newlines until "baseurl:"
  Web application consultancy with experts in Athens, OH and San Franscisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rakefire.io" # the base hostname & protocol for your site
social:
  twitter: rakefire
  facebook: hirerakefire
  github:  rakefire

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass