# Site settings
title: Rakefire
email: contact@rakefire.io
description: > # this means to ignore newlines until "baseurl:"
  Web application consultancy with experts in Athens, OH and San Franscisco, CA.
author:
keywords:
description:

logo: /images/rakefire_logo.png

company: Rakefire LLC
address_1: 29 East Carpenter
address_2: Athens, OH 45701

phone: (740) 561-1361

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rakefire.io" # the base hostname & protocol for your site
social:
  twitter:  rakefire
  facebook: hirerakefire
  github:   rakefire

testimonials: false

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass